project_id = "lhxbjlmrivynikkwgmce"

[functions.get-today-login-count]
verify_jwt = false

[functions.get-hourly-login-stats]
verify_jwt = false

[functions.get-login-stats-range]
verify_jwt = false

[functions.redeem-card]
verify_jwt = false

[functions.manage-cards]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.get-system-logs]
verify_jwt = false

[functions.add-system-log]
verify_jwt = false